/**
 * Mock Data for testing without API connection
 * Simulates real ticket data from the EGPB system
 */
import { Ticket, TicketStats, User } from '../types';

export const MOCK_USER: User = {
    id: 'user-001',
    username: 'admin',
    role: 'ADMIN',
    department: 'IT',
    email: 'admin@egpb.com',
    createdAt: '2024-01-01T00:00:00Z',
};

export const MOCK_STATS: TicketStats = {
    NEW: 8,
    IN_PROGRESS: 12,
    ON_HOLD: 3,
    DONE: 45,
    CANCEL: 2,
};

export const MOCK_ENGINEER_STATS: TicketStats = {
    NEW: 5,
    IN_PROGRESS: 9,
    ON_HOLD: 2,
    DONE: 38,
    CANCEL: 1,
};

export const MOCK_IT_TICKETS: Ticket[] = [
    {
        id: 'it-001',
        ticketNumber: 'IT-2502-001',
        title: 'Room 301 - WiFi Connection Issue',
        description: 'Guest reports intermittent WiFi disconnection in room 301. Signal strength appears normal but connection drops every 15 minutes.',
        department: 'Front Office',
        location: 'Guest room',
        typeOfDamage: 'Network / Internet / WIFI',
        status: 'NEW',
        createdAt: '2025-02-18T08:30:00Z',
        updatedAt: '2025-02-18T08:30:00Z',
        adminNotes: null,
        assignTo: null,
        user: { username: 'receptionist01' },
        images: [],
    },
    {
        id: 'it-002',
        ticketNumber: 'IT-2502-002',
        title: 'Back Office Printer Jam',
        description: 'HP LaserJet Pro in back office keeps jamming on A4 paper. Multiple paper jam alerts per day.',
        department: 'Executive & Accounting',
        location: 'Back Office',
        typeOfDamage: 'Printing / Scanning',
        status: 'IN_PROGRESS',
        createdAt: '2025-02-17T14:20:00Z',
        updatedAt: '2025-02-18T09:00:00Z',
        adminNotes: 'Ordered replacement roller kit. ETA: 2 days.',
        assignTo: 'tech_john',
        user: { username: 'accounting02' },
        images: [],
    },
    {
        id: 'it-003',
        ticketNumber: 'IT-2502-003',
        title: 'POS Terminal Frozen',
        description: 'POS terminal at restaurant cashier #2 is completely frozen. Cannot process payments.',
        department: 'F&B',
        location: 'Restaurant/Retail',
        typeOfDamage: 'POS',
        status: 'NEW',
        createdAt: '2025-02-18T10:15:00Z',
        updatedAt: '2025-02-18T10:15:00Z',
        adminNotes: null,
        assignTo: null,
        user: { username: 'restaurant_mgr' },
        images: [],
    },
    {
        id: 'it-004',
        ticketNumber: 'IT-2502-004',
        title: 'CCTV Camera 12 Offline',
        description: 'CCTV Camera #12 at parking lot entrance has gone offline. No video feed since yesterday evening.',
        department: 'Security',
        location: 'Public Area',
        typeOfDamage: 'CCTV',
        status: 'ON_HOLD',
        createdAt: '2025-02-16T22:00:00Z',
        updatedAt: '2025-02-17T11:30:00Z',
        adminNotes: 'Waiting for replacement camera. Current one has hardware failure.',
        assignTo: 'tech_mike',
        user: { username: 'security01' },
        images: [],
    },
    {
        id: 'it-005',
        ticketNumber: 'IT-2502-005',
        title: 'Email Access Issue',
        description: 'New employee cannot access company email. Account creation required for HR department.',
        department: 'Human Resource',
        location: 'Back Office',
        typeOfDamage: 'Email / Communication',
        status: 'DONE',
        createdAt: '2025-02-15T09:00:00Z',
        updatedAt: '2025-02-15T14:30:00Z',
        adminNotes: 'Account created and password sent via secure channel.',
        assignTo: 'admin',
        user: { username: 'hr_manager' },
        images: [],
    },
    {
        id: 'it-006',
        ticketNumber: 'IT-2502-006',
        title: 'Digital Signage Not Displaying',
        description: 'The digital signage screen in lobby is showing a black screen. Content was updated yesterday.',
        department: 'Front Office',
        location: 'Public Area',
        typeOfDamage: 'Television / Digital Signage',
        status: 'IN_PROGRESS',
        createdAt: '2025-02-17T07:45:00Z',
        updatedAt: '2025-02-18T08:00:00Z',
        adminNotes: 'HDMI cable replaced, checking media player.',
        assignTo: 'tech_john',
        user: { username: 'receptionist02' },
        images: [],
    },
    {
        id: 'it-007',
        ticketNumber: 'IT-2501-045',
        title: 'Software Update Required',
        description: 'All kitchen display screens need software update to latest version for new menu integration.',
        department: 'Kitchen',
        location: 'Kitchen',
        typeOfDamage: 'Software',
        status: 'DONE',
        createdAt: '2025-01-28T13:00:00Z',
        updatedAt: '2025-01-30T16:00:00Z',
        adminNotes: 'All 5 displays updated successfully.',
        assignTo: 'tech_mike',
        user: { username: 'kitchen_head' },
        images: [],
    },
    {
        id: 'it-008',
        ticketNumber: 'IT-2502-007',
        title: 'Access Card Reader Malfunction',
        description: 'Access card reader at floor 5 staff entrance is not reading any cards. Staff cannot enter without security escort.',
        department: 'Security',
        location: 'Back Office',
        typeOfDamage: 'Access Control',
        status: 'NEW',
        createdAt: '2025-02-18T06:30:00Z',
        updatedAt: '2025-02-18T06:30:00Z',
        adminNotes: null,
        assignTo: null,
        user: { username: 'security02' },
        images: [],
    },
    {
        id: 'it-009',
        ticketNumber: 'IT-2502-008',
        title: 'Laptop Hardware Issue',
        description: 'Accounting laptop screen flickering intermittently. Battery also drains quickly.',
        department: 'Executive & Accounting',
        location: 'Back Office',
        typeOfDamage: 'Hardware',
        status: 'CANCEL',
        createdAt: '2025-02-14T10:00:00Z',
        updatedAt: '2025-02-14T15:00:00Z',
        adminNotes: 'User received new laptop, old issue no longer relevant.',
        assignTo: null,
        user: { username: 'accounting01' },
        images: [],
    },
    {
        id: 'it-010',
        ticketNumber: 'IT-2502-009',
        title: 'Phone Extension Not Working',
        description: 'Extension 4521 in banquet office has no dial tone. Cannot make or receive calls.',
        department: 'Banquet',
        location: 'Back Office',
        typeOfDamage: 'Telephone',
        status: 'IN_PROGRESS',
        createdAt: '2025-02-17T16:00:00Z',
        updatedAt: '2025-02-18T10:00:00Z',
        adminNotes: 'Phone line traced. Issue with patch panel connection.',
        assignTo: 'tech_john',
        user: { username: 'banquet_coord' },
        images: [],
    },
];

export const MOCK_ENGINEER_TICKETS: Ticket[] = [
    {
        id: 'eng-001',
        ticketNumber: 'ENG-2502-001',
        title: 'Room 205 - AC Not Cooling',
        description: 'Air conditioning unit in room 205 is running but not providing cold air. Guest has complained.',
        department: 'Front Office',
        location: 'Guest Rooms',
        typeOfDamage: 'Air Condition',
        status: 'NEW',
        createdAt: '2025-02-18T09:00:00Z',
        updatedAt: '2025-02-18T09:00:00Z',
        adminNotes: null,
        assignTo: null,
        user: { username: 'receptionist01' },
        images: [],
    },
    {
        id: 'eng-002',
        ticketNumber: 'ENG-2502-002',
        title: 'Kitchen Hot Water Failure',
        description: 'Hot water supply to main kitchen has stopped. Boiler showing error code E05.',
        department: 'Kitchen',
        location: 'Kitchen',
        typeOfDamage: 'Hot Water',
        status: 'IN_PROGRESS',
        createdAt: '2025-02-17T06:30:00Z',
        updatedAt: '2025-02-18T07:00:00Z',
        adminNotes: 'Thermostat replaced. Monitoring temperature.',
        assignTo: 'eng_somchai',
        user: { username: 'kitchen_head' },
        images: [],
    },
    {
        id: 'eng-003',
        ticketNumber: 'ENG-2502-003',
        title: 'Lobby Lighting Flickering',
        description: 'Three LED panels in the main lobby are flickering. Affects guest impression.',
        department: 'Front Office',
        location: 'Office Hotel Area',
        typeOfDamage: 'Lighting',
        status: 'DONE',
        createdAt: '2025-02-15T11:00:00Z',
        updatedAt: '2025-02-16T14:00:00Z',
        adminNotes: 'LED drivers replaced for all three panels.',
        assignTo: 'eng_prayuth',
        user: { username: 'hk_supervisor' },
        images: [],
    },
    {
        id: 'eng-004',
        ticketNumber: 'ENG-2502-004',
        title: 'Room 412 - Toilet Leaking',
        description: 'Continuous water leak from toilet base in room 412. Floor is getting wet.',
        department: 'Housekeeping',
        location: 'Guest Rooms',
        typeOfDamage: 'Toilet',
        status: 'IN_PROGRESS',
        createdAt: '2025-02-18T07:15:00Z',
        updatedAt: '2025-02-18T08:30:00Z',
        adminNotes: 'Wax ring being replaced.',
        assignTo: 'eng_somchai',
        user: { username: 'hk_staff03' },
        images: [],
    },
    {
        id: 'eng-005',
        ticketNumber: 'ENG-2502-005',
        title: 'Function Room Door Stuck',
        description: 'The main door to Function Room B is very difficult to open. Hinge appears bent.',
        department: 'Banquet',
        location: 'Function Room',
        typeOfDamage: 'Door',
        status: 'ON_HOLD',
        createdAt: '2025-02-16T10:00:00Z',
        updatedAt: '2025-02-17T09:00:00Z',
        adminNotes: 'Need new heavy-duty hinge. Ordered from supplier.',
        assignTo: 'eng_prayuth',
        user: { username: 'banquet_coord' },
        images: [],
    },
];

// Simulate API delay
export function simulateDelay(ms: number = 800): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
}
